# Generated by Django 4.2.7 on 2026-05-27 17:11

import apps.accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('country', models.CharField(choices=[('CM', 'Cameroon'), ('GA', 'Gabon'), ('TD', 'Chad'), ('CF', 'Central African Republic'), ('GQ', 'Equatorial Guinea'), ('CG', 'Republic of the Congo')], default='CM', max_length=2)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('SUPER_ADMIN', 'Super Admin'), ('COMPLIANCE_ADMIN', 'Compliance Admin'), ('SECURITY_ADMIN', 'Security Admin'), ('SUPPORT_ADMIN', 'Support Admin'), ('PARTNER', 'Partner')], default='MEMBER', max_length=32)),
                ('trust_score', models.PositiveSmallIntegerField(default=0)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('kyc_rejection_reason', models.TextField(blank=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklisted_reason', models.TextField(blank=True)),
                ('fraud_flag_count', models.PositiveIntegerField(default=0)),
                ('last_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
