# Generated by Django 4.2.7 on 2026-05-27 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('pool_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active_members', models.PositiveIntegerField(default=1)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='airplane', max_length=54)),
                ('icon_bg', models.CharField(default='#06b6d41a', max_length=20)),
                ('icon_color', models.CharField(default='#00687a', max_length=20)),
                ('treasurer_name', models.CharField(blank=True, max_length=255)),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='tontines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
