# Generated by Django 4.2.7 on 2026-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('tontine_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=12)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default="L'application est temporairement en maintenance. Veuillez nous excuser pour le désagrément.")),
            ],
            options={
                'verbose_name': 'Paramètre de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
    ]
